#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP -d 1 2 3 4 5
bspc monitor DisplayPort-0 -d 1 2 3 4 5 


# bspc monitor eDP -d I II III IV V
# bspc monitor DisplayPort-0 -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12
bspc config bottom_padding 6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_follows_monitor true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_slide
bspc config pointer_action3 resize_corner

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

#Colors
bspc config normal_border_color     "#eee5e9" 
bspc config active_border_color     "#fb6376"
bspc config focused_border_color    "#fb6376"
bspc config presel_feedback_color   "#01baef"
bspc config urgent_border_color     "#ffca3a"

~/.config/bspwm/autostart.sh

